#  Lina Vanessa Vera Pulido-1151998

#  Ronaldo Rafael Arias Parada- 1151674                     

Dataset: https://drive.google.com/file/d/1i9BpbI7PHjP8FkDtkna1mc5FCs1XROaT/view?usp=sharing

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score, f1_score, classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# en COLABORATORY
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
#Leyendo el dataset
tree=pd.read_csv("covtype.csv")
tree.head()

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0       2596      51      3                               258   
1       2590      56      2                               212   
2       2804     139      9                               268   
3       2785     155     18                               242   
4       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0            221             232            148   
1            220             235            151   
2            234             238            135   
3            238             238            122   
4            220             234            150   

   Horizontal_Distance_To_Fire_Points  ...  Soil_Type32  Soil_Type33  \
0                                6279  ...            0            0   
1                                6225  ...            0            0   
2                                6121  ...            0            0   
3                                6211  ...            0            0   
4                                6172  ...            0            0   

   Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  Soil_Type38  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type39  Soil_Type40  Cover_Type  
0            0            0           5  
1            0            0           5  
2            0            0           2  
3            0            0           2  
4            0            0           5  

[5 rows x 55 columns]

In [4]:
#Dimensiones del dataset
print(tree.shape)

(581012, 55)


In [5]:
#obteniendo la información del dataset
tree.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581012 entries, 0 to 581011
Data columns (total 55 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           581012 non-null  int64
 1   Aspect                              581012 non-null  int64
 2   Slope                               581012 non-null  int64
 3   Horizontal_Distance_To_Hydrology    581012 non-null  int64
 4   Vertical_Distance_To_Hydrology      581012 non-null  int64
 5   Horizontal_Distance_To_Roadways     581012 non-null  int64
 6   Hillshade_9am                       581012 non-null  int64
 7   Hillshade_Noon                      581012 non-null  int64
 8   Hillshade_3pm                       581012 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  581012 non-null  int64
 10  Wilderness_Area1                    581012 non-null  int64
 11  Wilderness_Area2                    581012 non-null 

In [6]:
#Verificar si existen valores NaN
tree.isnull().sum()

Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0


In [7]:
#Describiendo el dataset
tree.describe()

Elevation         Aspect          Slope  \
count  581012.000000  581012.000000  581012.000000   
mean     2959.365301     155.656807      14.103704   
std       279.984734     111.913721       7.488242   
min      1859.000000       0.000000       0.000000   
25%      2809.000000      58.000000       9.000000   
50%      2996.000000     127.000000      13.000000   
75%      3163.000000     260.000000      18.000000   
max      3858.000000     360.000000      66.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                     581012.000000                   581012.000000   
mean                         269.428217                       46.418855   
std                          212.549356                       58.295232   
min                            0.000000                     -173.000000   
25%                          108.000000                        7.000000   
50%                          218.000000                       30.000000   
75%                          384.000000                       69.000000   
max                         1397.000000                      601.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                    581012.000000  581012.000000   581012.000000   
mean                       2350.146611     212.146049      223.318716   
std                        1559.254870      26.769889       19.768697   
min                           0.000000       0.000000        0.000000   
25%                        1106.000000     198.000000      213.000000   
50%                        1997.000000     218.000000      226.000000   
75%                        3328.000000     231.000000      237.000000   
max                        7117.000000     254.000000      254.000000   

       Hillshade_3pm  Horizontal_Distance_To_Fire_Points  ...    Soil_Type32  \
count  581012.000000                       581012.000000  ...  581012.000000   
mean      142.528263                         1980.291226  ...       0.090392   
std        38.274529                         1324.195210  ...       0.286743   
min         0.000000                            0.000000  ...       0.000000   
25%       119.000000                         1024.000000  ...       0.000000   
50%       143.000000                         1710.000000  ...       0.000000   
75%       168.000000                         2550.000000  ...       0.000000   
max       254.000000                         7173.000000  ...       1.000000   

         Soil_Type33    Soil_Type34    Soil_Type35    Soil_Type36  \
count  581012.000000  581012.000000  581012.000000  581012.000000   
mean        0.077716       0.002773       0.003255       0.000205   
std         0.267725       0.052584       0.056957       0.014310   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

         Soil_Type37    Soil_Type38    Soil_Type39    Soil_Type40  \
count  581012.000000  581012.000000  581012.000000  581012.000000   
mean        0.000513       0.026803       0.023762       0.015060   
std         0.022641       0.161508       0.152307       0.121791   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

          Cover_Type  
count  581012.000000  
mean        2.051471  
std         1.396504  
min         1.000000  
25%         1.000000  
50%         2.000000  
75%         2.000000  
max         7.000000  

[8 rows x 55 colu

# EDA

In [8]:
#Obteniendo los tipos de datos del dataset
tree.dtypes

Elevation                             int64
Aspect                                int64
Slope                                 int64
Horizontal_Distance_To_Hydrology      int64
Vertical_Distance_To_Hydrology        int64
Horizontal_Distance_To_Roadways       int64
Hillshade_9am                         int64
Hillshade_Noon                        int64
Hillshade_3pm                         int64
Horizontal_Distance_To_Fire_Points    int64
Wilderness_Area1                      int64
Wilderness_Area2                      int64
Wilderness_Area3                      int64
Wilderness_Area4                      int64
Soil_Type1                            int64
Soil_Type2                            int64
Soil_Type3                            int64
Soil_Type4                            int64
Soil_Type5                            int64
Soil_Type6                            int64
Soil_Type7                            int64
Soil_Type8                            int64
Soil_Type9                      

Dado que todos los tipos de datos son int64, solo necesitamos escalar nuestras características para asegurarnos de que estén en la misma escala para entrenar nuestro modelo.

In [9]:
tree = tree.dropna()

In [10]:
x = tree.iloc[:, 0:13]
y = tree.iloc[:, -1]

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [12]:
escalar = StandardScaler()
x_train = escalar.fit_transform(x_train)
x_test = escalar.transform(x_test)

In [13]:
# Ahora, necesitamos normalizar los datos.
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Regresión Logisica.

In [18]:
modeloRL = LogisticRegression()
modeloRL.fit(x_train, y_train.values.ravel())
pred_RL = modeloRL.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [19]:
#Matriz de confusión del modelo Regresión logistica.
matrizC = confusion_matrix(y_test, pred_RL)
matrizC

array([[37257, 14973,     2,     0,     0,     4,   840],
       [13854, 55745,   796,    85,     0,   250,     5],
       [    0,  1572,  6477,    73,     0,   663,     0],
       [    0,     1,   644,    19,     0,    47,     0],
       [    4,  2370,    19,     0,     0,     1,     0],
       [    0,  1355,  2448,    41,     0,   625,     0],
       [ 3148,    65,     0,     0,     0,     0,  1870]])

In [20]:
#MÉTRICAS DE LA MATRIZ DE CONFUSIÓN DEL MODELO DE REGRESIÓN LOGISTICA.

exactitudMRL = accuracy_score(y_test, pred_RL)
print("Exactitud ", exactitudMRL)

puntajef1MRL = f1_score(y_test, pred_RL, average='weighted')
print("Puntaje F1 ", puntajef1MRL)

clasificacionMRL = classification_report(y_test, pred_RL)
print("Clasificación", clasificacionMRL)

Exactitud  0.702174825993267
Puntaje F1  0.6876633900911485
Clasificación               precision    recall  f1-score   support

           1       0.69      0.70      0.69     53076
           2       0.73      0.79      0.76     70735
           3       0.62      0.74      0.68      8785
           4       0.09      0.03      0.04       711
           5       0.00      0.00      0.00      2394
           6       0.39      0.14      0.21      4469
           7       0.69      0.37      0.48      5083

    accuracy                           0.70    145253
   macro avg       0.46      0.39      0.41    145253
weighted avg       0.68      0.70      0.69    145253



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# K-NN

In [15]:
from sklearn.neighbors import KNeighborsClassifier
cKNN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
cKNN.fit(x_train, y_train.values.ravel())
pred_knn = cKNN.predict(x_test)
pred_knn

array([2, 1, 3, ..., 1, 1, 2])

In [16]:
matrizKNN = confusion_matrix(y_test, pred_knn)
matrizKNN

array([[48935,  3857,     7,     0,    39,    10,   228],
       [ 3259, 66749,   226,     8,   274,   187,    32],
       [   11,   278,  7943,    55,    12,   486,     0],
       [    0,     1,   143,   527,     0,    40,     0],
       [   61,   474,    37,     0,  1813,     9,     0],
       [   15,   289,   501,    36,     9,  3619,     0],
       [  368,    57,     0,     0,     0,     0,  4658]])

In [17]:
exactitudknn = accuracy_score(y_test, pred_knn)
print("Exactitud: ",exactitudknn)
puntajef1KNN = f1_score(y_test, pred_knn, average = 'weighted')
print("F1: ",puntajef1KNN)

clasificacionKNN = classification_report(y_test, pred_knn)
print(clasificacionKNN)

Exactitud:  0.9242081058566777
F1:  0.9239881717168661
              precision    recall  f1-score   support

           1       0.93      0.92      0.93     53076
           2       0.93      0.94      0.94     70735
           3       0.90      0.90      0.90      8785
           4       0.84      0.74      0.79       711
           5       0.84      0.76      0.80      2394
           6       0.83      0.81      0.82      4469
           7       0.95      0.92      0.93      5083

    accuracy                           0.92    145253
   macro avg       0.89      0.86      0.87    145253
weighted avg       0.92      0.92      0.92    145253



# Naive Bayes

In [21]:
algoritmNB = GaussianNB()
algoritmNB.fit(x_train, y_train.values.ravel())
pred_NB = algoritmNB.predict(x_test)

In [22]:
#Matriz de confusión del algoritmo Naive bayes.
matrizNB = confusion_matrix(y_test, pred_NB)
matrizNB

array([[18778,  5020, 10959,     0,  8299,  7551,  2469],
       [ 6330, 10592, 19066,   664, 22594, 10560,   929],
       [    0,     0,  3526,  4625,     0,   634,     0],
       [    0,     0,     0,   711,     0,     0,     0],
       [    0,    69,   851,     0,   871,   603,     0],
       [    0,     0,   779,  2384,     0,  1306,     0],
       [ 2039,     2,  1427,     0,    22,   162,  1431]])

In [23]:
#MÉTRICAS DE LA MATRIZ DE CONFUSIÓN DEL ALGORITMO NAIVE BAYES.
exactitudANB = accuracy_score(y_test, pred_NB)
print("Exactitud ",exactitudANB)

puntajef1ANB = f1_score(y_test, pred_NB, average='weighted')
print("Puntaje F1 ",puntajef1ANB)

clasificacionANB = classification_report(y_test, pred_NB)
print("Clasificación", clasificacionANB)

Exactitud  0.2562081333948352
Puntaje F1  0.3147206621127707
Clasificación               precision    recall  f1-score   support

           1       0.69      0.35      0.47     53076
           2       0.68      0.15      0.25     70735
           3       0.10      0.40      0.16      8785
           4       0.08      1.00      0.16       711
           5       0.03      0.36      0.05      2394
           6       0.06      0.29      0.10      4469
           7       0.30      0.28      0.29      5083

    accuracy                           0.26    145253
   macro avg       0.28      0.41      0.21    145253
weighted avg       0.60      0.26      0.31    145253



# Random Forest

In [24]:
algoritmRFC = RandomForestClassifier()
algoritmRFC.fit(x_train, y_train.values.ravel())
pred_rfc = algoritmRFC.predict(x_test)

In [25]:
#Matriz de confusión del algoritmo random forest para clasificación.
matrizRFC = confusion_matrix(y_test, pred_rfc)
matrizRFC

array([[50104,  2878,     1,     0,    11,     5,    77],
       [ 1699, 68683,   161,     4,    85,    85,    18],
       [    2,   146,  8413,    35,     6,   183,     0],
       [    0,     0,    88,   602,     0,    21,     0],
       [   26,   545,    31,     0,  1786,     6,     0],
       [    4,   169,   294,    24,     6,  3972,     0],
       [  317,    30,     0,     0,     0,     0,  4736]])

In [26]:
#MÉTRICAS DE LA MATRIZ DE CONFUSIÓN DEL ALGORITMO RANDOM FOREST PARA CLASIFICACIÓN.
exactitudARFC = accuracy_score(y_test, pred_rfc)
print("Exactitud ",exactitudARFC)

puntajef1ARFC = f1_score(y_test, pred_rfc, average='weighted')
print("Puntaje F1 ",puntajef1ARFC)

clasificacionARFC = classification_report(y_test, pred_rfc)
print("Clasificación", clasificacionARFC)

Exactitud  0.9521042594645205
Puntaje F1  0.9518221629470157
Clasificación               precision    recall  f1-score   support

           1       0.96      0.94      0.95     53076
           2       0.95      0.97      0.96     70735
           3       0.94      0.96      0.95      8785
           4       0.91      0.85      0.88       711
           5       0.94      0.75      0.83      2394
           6       0.93      0.89      0.91      4469
           7       0.98      0.93      0.96      5083

    accuracy                           0.95    145253
   macro avg       0.94      0.90      0.92    145253
weighted avg       0.95      0.95      0.95    145253



# Conclusión.

In [27]:
#EL mejor modelo es el realizado por el algoritmo de Random Forest para clasificación para los siguientes valores:
print("Exactitud ", exactitudARFC)
print("Puntaje F1 ", puntajef1ARFC)

Exactitud  0.9521042594645205
Puntaje F1  0.9518221629470157
