<font color=Green>
    
# **2.4 Álgebra lineal**

</font>

## <font color=#003d5c>_Producto de arrays_ </font>

In [1]:
import numpy as np

a = np.array([1, 2, 3], float) 
b = np.array([0, 1, 1], float) 

np.dot(b, a)

5.0

In [2]:
a.dot(b)

5.0

## <font color=#003d5c>_Producto de matrices_ </font>

In [3]:
a = np.array([[5, 2], [4, 8]], float) 
b = np.array([[2, 4], [5, 3]], float) 

print(a, "\n ---------------")
print(b, "\n ---------------")

[[5. 2.]
 [4. 8.]] 
 ---------------
[[2. 4.]
 [5. 3.]] 
 ---------------


In [4]:
np.dot(a, b)

array([[20., 26.],
       [48., 40.]])

In [5]:
a @ b

array([[20., 26.],
       [48., 40.]])

In [6]:
a = np.array([[0, 1, 4], [5, 2, 3], [1, 4, 8]], float) 

b = np.array([2, 3, 5], float) 

print(b,"\n ---------------")
print(a, "\n ---------------")

[2. 3. 5.] 
 ---------------
[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]] 
 ---------------


In [7]:
np.dot(a,b)

array([23., 31., 54.])

In [ ]:
a @ b

In [8]:
print(np.matmul(a,b))

[23. 31. 54.]


## <font color=#003d5c>_Determinante de una matriz_ </font>

In [9]:
a = np.array([[8, 5], [3, 4]])

print(a, "\n ---------------")

np.linalg.det(a)

[[8 5]
 [3 4]] 
 ---------------


17.0

## <font color=#003d5c>_Auto-valores y auto-vectores_ </font>

In [10]:
vals, vecs = np.linalg.eig(a)

print(vals, "\n ---------------")
print(vecs, "\n ---------------")

[10.35889894  1.64110106] 
 ---------------
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
 ---------------
