## <font color=green> 2.5 Funciones universales Unarias </font>

### Son funciones que realizan operaciones elemento a elemento sobre datos en un   `ndarray`. 

### Las funciones _unarias_ comprenden todas las operaciones que reciben un solo array como argumento.

|Función|Descripción|
|-------|-----------|
|`abs`, `fabs`|Calcular el valor absoluto|
|`sqrt`|Calcular la raíz cuadrada|
|`square`|Calcular el cuadrado|
|`exp`|Calcular la exponencial $e^x$|
|`log`, `log10`, `log2`, `log1p`|Calcula el Logaritmo natural, en base a 10, 2, y $log(x + 1)$|
|`isnan`|Devuelve un array booleano indicando si cada elemento es NaN (Not a Number)|
|`sin, cos, tan`| Devuelve un array con el resultado de aplicar la función seno, coseno, y tangente en los valores|
|`mean, median, std, var`|Calcula la media aritmética, la mediana, la desviación estándard y la varianza en un array|

In [1]:
import numpy as np

a = np.array([2, 4, 9], float)

In [2]:
a

array([2., 4., 9.])

In [13]:
np.abs(a)

array([2., 4., 9.])

In [3]:
np.sqrt(a)

array([1.41421356, 2.        , 3.        ])

In [14]:
np.isnan(a)

array([False, False, False])

In [11]:
np.square(a)

array([ 4., 16., 81.])

In [4]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [5]:
np.log(a)

array([0.69314718, 1.38629436, 2.19722458])

In [6]:
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.41211849])

In [7]:
np.cos(a)

array([-0.41614684, -0.65364362, -0.91113026])

In [12]:
np.tan(a)

array([-2.18503986,  1.15782128, -0.45231566])

In [8]:
np.mean(a)

5.0

In [9]:
np.std(a)

2.943920288775949

In [10]:
np.var(a)

8.666666666666666