## <font color=green> 2.6 Funciones Universales Binarias </font>

### Son funciones que realizan operaciones elemento-a-elemento sobre datos en una   `ndarray`. 

### Las funciones _binarias_ toman dos arrays y devuelven uno o más arrays.

|Función|Descripción|
|-------|-----------|
|`add`|Suma entre elementos correspondientes entre arrays|
|`subtract`|Resta entre elementos de arrays|
|`multiply`|Multiplica arrays|
|`divide`, `floor_divide`|Divide o división truncada|
|`array_equal`|Devuelve `True` si los elementos del array son iguales entre sí|
|`power`|Eleva cada elemento del primer array a la potencia indicada en el segundo array|
|`fmin`|Devuelve el mínimo entre cada elemento. `fmin` ignora los `NaN`|
|`fmax`|Devuelve el máximo entre cada elemento. `fmax` ignora los `NaN`|


In [1]:
import numpy as np

arr = np.array([5,36,17,18,9])

arr_2 = np.array([8,24,17,19,9])

In [2]:
np.add(arr,arr_2)

array([13, 60, 34, 37, 18])

In [3]:
np.subtract(arr,arr_2)

array([-3, 12,  0, -1,  0])

In [4]:
np.multiply(arr,arr_2)

array([ 40, 864, 289, 342,  81])

In [5]:
np.divide(arr,arr_2)

array([0.625     , 1.5       , 1.        , 0.94736842, 1.        ])

In [6]:
np.array_equal(arr,arr_2)

False

In [9]:
np.power(arr,arr_2)

array([    390625,          0, 1681328401, -355991552,  387420489],
      dtype=int32)

In [7]:
np.fmin(arr,arr_2)

array([ 5, 24, 17, 18,  9])

In [8]:
np.fmax(arr,arr_2)

array([ 8, 36, 17, 19,  9])