<font color=Green>
    
# **2.8 Transformaciones**

</font>


## <font color=#003d5c>_As Type_ </font>

### Este método nos permite modificar el tipo de dato de los valores de un `array`

In [1]:
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[20, 27, 49, 96],
       [11, 19, 15, 27],
       [26, 64, 38, 60]])

In [2]:
arr_ent.astype(float)

array([[20., 27., 49., 96.],
       [11., 19., 15., 27.],
       [26., 64., 38., 60.]])

## <font color=#003d5c>_Sort_ </font>

### Este método nos permite ordenar los valores de un `array`

In [3]:
arr_ent

array([[20, 27, 49, 96],
       [11, 19, 15, 27],
       [26, 64, 38, 60]])

In [4]:
arr_ent.sort()
arr_ent

array([[20, 27, 49, 96],
       [11, 15, 19, 27],
       [26, 38, 60, 64]])

In [5]:
arr_ent.sort(axis=0)
arr_ent

array([[11, 15, 19, 27],
       [20, 27, 49, 64],
       [26, 38, 60, 96]])

## <font color=#003d5c>_Reshape_ </font>

### Este método nos permite modificar las dimensiones de un `array`.

In [6]:
arr_ent

array([[11, 15, 19, 27],
       [20, 27, 49, 64],
       [26, 38, 60, 96]])

In [7]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[11, 15, 19],
       [27, 20, 27],
       [49, 64, 26],
       [38, 60, 96]])

## <font color=#003d5c>_Flatten_ </font>

### Este método crea un array unidimensional desde el original.

In [8]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[11 15 19]
 [27 20 27]
 [49 64 26]
 [38 60 96]]
[11 15 19 27 20 27 49 64 26 38 60 96]


## <font color=#003d5c>_To List_ </font>

### Este método crea una lista a partir de un array

In [12]:
lista_arr = plano_arr.tolist()
type(lista_arr)
lista_arr

[11, 15, 19, 27, 20, 27, 49, 64, 26, 38, 60, 96]

## <font color=#003d5c>_Separar y juntar arrays_ </font>

In [10]:
arrays= np.split(arr_ent,4)
arrays

[array([[11, 15, 19]]),
 array([[27, 20, 27]]),
 array([[49, 64, 26]]),
 array([[38, 60, 96]])]

In [13]:
np.concatenate((arrays[1],arrays[0]),axis=1)

array([[27, 20, 27, 11, 15, 19]])

## <font color=#003d5c>_La matriz transpuesta_ </font>

In [14]:
arr_ent

array([[11, 15, 19],
       [27, 20, 27],
       [49, 64, 26],
       [38, 60, 96]])

In [15]:
t_arr = arr_ent.T
t_arr

array([[11, 27, 49, 38],
       [15, 20, 64, 60],
       [19, 27, 26, 96]])